<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
</head>
<body>
<textarea id="code_snippet" style="width: 448px; height: 68px;">// write your code here</textarea>
<br>
<button id="send_snippet" type="submit" onclick="send()">Submit</button>
<br>
Time restriction: <input id="time_restriction" style="display: inline-block" type="text"/>
<br>
Views restriction: <input id="views_restriction" style="display: inline-block" type="text"/>
</body>
</html>